name: Make repository public and self-destruct

on:
  schedule:
    - cron: '0 0 1 4 *'  # Runs at 00:00 UTC on April 1st

jobs:
  make-public-and-delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checks out the repository so we can modify it

      - name: Make repo public
        run: |
          curl -L -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MY_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{"private": false}'

      - name: Delete this workflow file
        run: |
          git rm .github/workflows/make-public.yml
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Self-destruct: Removed workflow file after making repo public"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
